Refactor: withdraw per challenge
AlibudaLab/nouns-habit-builder pull request #32
Opened 2024-05-19 16:14 UTC by ottbunn

# Summary

 update the withdraw logic to withdraw based on each challenge

2024-05-20 08:27 UTC, ryanycw commented on contracts/test/Tracker.t.sol
> +        require(tracker.getClaimableAmount(0, address(this)) == 0.0001 ether, "Settle failed");
```suggestion
        require(tracker.getClaimableAmount(0, address(this)) == PER_USER_STAKE, "Settle failed");
```

2024-05-20 08:33 UTC, antoncoding requested changes
I think double withdrawal is not prevented

2024-05-20 08:33 UTC, antoncoding commented on contracts/src/Tracker.sol
> +            uint256 balance = challenges[challengeId].totalStake;
just call it `stake` or `amount`. It's not a balance

2024-05-20 08:33 UTC, antoncoding commented on contracts/src/Tracker.sol
> +        IERC20(underlyingToken).safeTransfer(msg.sender, amount);
There should be a double claim protection

2024-05-20 08:33 UTC, antoncoding commented on contracts/test/Tracker.t.sol
> +        tracker.join(0);
we should update the contract so that the ID doesn't start with 0, looks very weird.

2024-05-20 08:33 UTC, antoncoding commented on contracts/test/Tracker.t.sol
> +    function test_withdraw_failed_user(address failedUser, uint256 timestamp) public {
better use some prefix like `test_RevertWhen` to indicate that this test is expected to revert.
This way people can use flags like `--match-test` to exclude these tests when running gas reports.

Ref: https://github.com/sablier-labs/v2-core/blob/9657fbd0a77821a088b34d460dd1117e5600bb43/test/unit/concrete/adminable/transfer-admin/transferAdmin.t.sol#L9

2024-05-20 08:35 UTC, ryanycw commented on contracts/test/Tracker.t.sol
> +        uint256 failedUserBalance = underlying.balanceOf(failedUser);
```suggestion
```

2024-05-20 08:41 UTC, antoncoding commented on contracts/src/Tracker.sol
> +        if (succeedUserCounts > 0) {
Agree, we can add function in the future that does:
If settled and succeeded == 0, transfer other half to owner address

Doesn't have to be handled here.

2024-05-22 02:53 UTC, antoncoding approved these changes

2024-05-22 02:53 UTC, antoncoding commented on contracts/src/Tracker.sol
> +        require(claimable[challengeId][msg.sender], "user not eligible or already claimed");
I don't think we have to check here: if claimable is false, `getClaimableAmount` is going to be 0. The check is duplicated, can just throw on amount == 0.

2024-05-22 08:29 UTC, ryanycw approved these changes
Others look good!! Thank you so much :)

2024-05-22 08:29 UTC, ryanycw commented on contracts/src/Tracker.sol
> +    uint256 public challengeCounter = 1;
```suggestion
    uint256 public challengeCounter;
```

2024-05-22 08:29 UTC, ryanycw commented on contracts/src/Tracker.sol
> +    uint256 public challengeCounter = 1;
And make L66
```
challenges[++challengeCounter] =
```

2024-05-24 14:13 UTC, merged